### ISSUE TITLE
最符合原文

### ISSUE THREAD

**Issue by stevewyl** [HaishuoFang/DPCNN#1]
看了github上其他的实现，你的这个版本最符合原文的模型结构

**Comment by stevewyl** [comment]
第63行，直接用squeeze会不会太粗暴了 文中用的是max_pooling吧 
conv3 = tf.squeeze(conv3, [1, 2])  # [batch,250]

**Comment by HaishuoFang** [comment]
这边squeeze是因为通过反复的maxpooling之后，最后都被压缩成了一维，所以可以直接squeeze，dims=1的维度，原文pyramid的思想就是这样

**Comment by yanfan0531** [comment]
> 这边squeeze是因为通过反复的maxpooling之后，最后都被压缩成了一维，所以可以直接squeeze，dims=1的维度，原文pyramid的思想就是这样

想问一下，在_block函数里，为什么要先做padding？
